name: vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file:
      - .env
    ports:
      - "127.0.0.1:8666:80"
    volumes:
      - ${DATA_LOCATION:-./vw-data}:/data
      - ${DATA_LOCATION:-./vw-data}/logs:/data/logs
    restart: always