services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    networks: 
      crowdsec:
        ipv4_address: 172.28.0.10
      # Uncomment the next line if you have already configured Traefik and the 'proxy' network
      # proxy:
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 127.0.0.1:8080:8080 # port mapping for local firewall bouncers
    expose:
      - 8080 # http api for bouncers
      - 7422 # appsec waf endpoint
      # - 6060 # metrics endpoint for prometheus
    volumes:
      # crowdsec container data
      - ./crowdsec:/etc/crowdsec
      - cs_data:/var/lib/crowdsec/data
      # log bind mounts into crowdsec
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - ${TRAEFIK_LOGS_FOLDER:-/var/log/traefik}:/var/log/traefik:ro  # Traefik integration
    environment:
      - TZ=Europe/Rome
      - GID=${GID-1000}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "cscli", "lapi", "status"]
      interval: 10s
      timeout: 5s
      retries: 15

  database:
    image: postgres:latest
    container_name: crowdsec_database
    restart: unless-stopped
    networks: [crowdsec]
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
      - POSTGRES_DB=crowdsec
    volumes:
      - database:/var/lib/postgresql
    secrets:
      - pg_password

secrets:
  pg_password:
    file: ./secrets/pg_password.txt

volumes:
  cs_data:
  database:

networks:
  crowdsec:
    name: crowdsec
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
# Uncomment next lines if you have already configured Traefik and the 'proxy' network
#   proxy:
#     external: true